//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases
    {
        public int CaseId { get; set; }
        public string CaseName { get; set; }
        public Nullable<decimal> Accumulation { get; set; }
        public Nullable<decimal> Inside { get; set; }
        public Nullable<decimal> OutTo { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Statuses Statuses { get; set; }
    }
}
