//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CustomerId { get; set; }
        public string NameSurname { get; set; }
        public string IdentityNumber { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Photograph1 { get; set; }
        public string Photograph2 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> TownId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Towns Towns { get; set; }
    }
}
