//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        public int PhoneId { get; set; }
        public string Description { get; set; }
        public string Phone { get; set; }
        public int StatusId { get; set; }
    
        public virtual Statuses Statuses { get; set; }
    }
}
