//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMovements
    {
        public int MovementId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string MovementType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
