//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ReservationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string People { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string ReservationNameSurname { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
